# Generated by Django 4.0.4 on 2022-05-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Path',
            field=models.CharField(choices=[('0', '-----------'), ('1', 'Full Stack'), ('2', 'AWS-DevOps'), ('3', 'Data Science'), ('4', 'Cyber Security')], max_length=20),
        ),
    ]
